### ISSUE TITLE
How to use /rename command

### ISSUE THREAD

**Issue by drmetro09** [jsavargas/telegram-downloader-bot#5]
Hi , i need help as how to use /rename command , basically want to rename files when they get downloaded, remove some words from the file name … how do i do it ? Need some explanation/tutorial

**Comment by jsavargas** [comment]
/rename without anything else, returns the name to how it was originally according to the rules you have applied either for the group, extension or name


![image](https://github.com/user-attachments/assets/9498f92f-0b2c-43a9-bd6c-f54f0e594a30)

**Comment by drmetro09** [comment]
/rename command gives error: File renamed Exception:’NoneType’ object is not iterable @jsavargas

**Comment by drmetro09** [comment]
And how to set the config file rules for rename?

**Comment by jsavargas** [comment]
Can you post an example of where you used it? Look at the screenshot I posted, it is used with the reply from the file you downloaded.

**Comment by jsavargas** [comment]
One of the rules could be that a mobi extension file is downloaded to a specific folder, then you give it /rename and move that file to another path, I will give some examples later.

**Comment by drmetro09** [comment]
I didn’t understand it brother it sounds complex… on telegram I just give /rename newname as a reply to the file downloaded but i get that error I mention in previous message

**Comment by drmetro09** [comment]
Can you please tell me how to configure rename in config because im unable to use the rename command

**Comment by jsavargas** [comment]
/rename new-name

This is by replying to the same file that you sent to the bot

**Comment by jsavargas** [comment]
Can you put a screenshot of the error?

**Comment by drmetro09** [comment]
> /rename new-name
> 
> This is by replying to the same file that you sent to the bot

Does this work , if the file sent to the bot is forwarded from some other group?

**Comment by jsavargas** [comment]
It should work

**Comment by drmetro09** [comment]
Can we discuss on discord ?

**Comment by jsavargas** [comment]
https://discord.gg/FdJMau8sf6

I have created a new channel for this project

**Comment by drmetro09** [comment]
The /rename command doesnt work if we send it along with the forwarded file
