### ISSUE TITLE
Slow speed with the new update 

### ISSUE THREAD

**Issue by drmetro09** [jsavargas/telegram-downloader-bot#7]
I recently updated to latest and the speed drastically dropped from 30 mbps to just 16 mbps

**Comment by jsavargas** [comment]
It still downloads at acceptable speeds for me (40mbps), it is likely that the more you use the bot, Telegram will start limiting your download.

**Comment by jsavargas** [comment]
![Screenshot_20241204-011503_Telegram](https://github.com/user-attachments/assets/714cd99f-c4a3-4df8-8753-bc3888a15313)
